# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: '#about'
    weight: 10
  - name: Skills
    url: 'skills/'
    weight: 20
  - name: Experience
    url: 'experience/'
    weight: 30
  - name: Projects
    url: 'project'
    weight: 40
